### ISSUE TITLE
"CompressionCount" being double charged?

### ISSUE THREAD

**Issue by ChrisInSeattle** [tinify/tinify-net#13]
I have the following code:
`public async Task<byte[]> CompressImageFromUrlAsync(string url)
        {
            var a1 = Tinify.CompressionCount;
            var source =
                await Tinify.FromUrl(url).ConfigureAwait(false); // <- CompressionCount inc here 
            var a2 = Tinify.CompressionCount;
            var copyrighted = source.Preserve("copyright");
            var a3 = Tinify.CompressionCount;
            var outputBuffer = await copyrighted.ToBuffer().ConfigureAwait(false); // <- CompressionCount inc here 
            var a4 = Tinify.CompressionCount;

            Debug.WriteLine($"CompressImageFromUrl checkpoints: {a1}, {a2}, {a3}, {a4}");

            return outputBuffer;
        }`

It looks like my CompressionCount is being double charged. It's incremented in both the FromUrl() call and the ToBuffer() call. Unless I'm missing something.. ?

**Comment by tinify-support** [comment]
Hi,

Thanks for contacting us. After some testing it seems that
changing the metadata (i.e. keeping it) increments the count
value. We will look into this but in the meantime can you please
send us your TinyPNG email so that we credit your account for the
extra incurred compressions.

Looking forward to hearing from you.

Kind regards,

Evert Rotshuizen

We are always looking for ways to improve our products. Click
here ( https://insights.hotjar.com/s?siteId=648131&surveyId=28591 )  to give us your opinion (it will take less than 1 minute).

tinify/tinify-net on December 12, 2017 at 8:48pm wrote:

I have the following code:

`public async Task<byte[]> CompressImageFromUrlAsync(string url)

{

var a1 = Tinify.CompressionCount;

var source =

await Tinify.FromUrl(url).ConfigureAwait(false); // <-
CompressionCount inc here

var a2 = Tinify.CompressionCount;

var copyrighted = source.Preserve("copyright");

var a3 = Tinify.CompressionCount;

var outputBuffer = await
copyrighted.ToBuffer().ConfigureAwait(false); // <-
CompressionCount inc here

var a4 = Tinify.CompressionCount;

Debug.WriteLine($"CompressImageFromUrl checkpoints: {a1}, {a2},
{a3}, {a4}");

return outputBuffer;
}`

It looks like my CompressionCount is being double charged. It's
incremented in both the FromUrl() call and the ToBuffer() call.
Unless I'm missing something.. ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
( https://github.com/tinify/tinify-net/issues/13 ), or mute the
thread
