### ISSUE TITLE
Allow the possibility to skip ca certificates validation

### ISSUE THREAD

**Issue by joaomatossilva** [tinify/tinify-net#6]
For non windows platforms there are some issues with the certificates validations on nonssl installs. There should be a workaround to skip that validation while Microsoft works on this issue

**Comment by zolakt** [comment]
From what I can tell it doesn't work on any non-windows platforms.
Works locally on Windows, when I deploy it on Linux, I get a "SSL connection error".

Could it be related to this problem?
https://stackoverflow.com/questions/41774381/x509certificatevalidationmode-not-working-in-linux

Can you just make a flag to turn off validation completely?
It's making the lib unusable in production.
Currently I'll have to drop it completely and switch to another client.

My suggestion would be to make the HttpClientHandler injectable, but since this whole lib is "static galore", I guess that's not really an option. So just stick a property to the main Tinify class.

**Comment by viktor-gustafsson** [comment]
Can you please merge the PR as it would be nice to be able to run Tinify inside a linux docker container.

**Comment by EllinorBergman** [comment]
What version of Linux are you using? We have used Ubuntu version 18.04 as well as 16.04 running .NET core 3.0, and we are unable to reproduce it.

**Comment by quentinR0bert** [comment]
Hi ! 
On MacOS, use in a .netstandar library and use into a .netCore CLI, since the 20 September (Let'sEncryp root CA expiration ?),  we always have this exception : "Error while connecting: The remote certificate is invalid according to the validation procedure". (Even with the 1.5.3 version).
Do you have in the futur an update for this, or will we need to use the fork of matthewrdev ?

**Comment by rkoopmans** [comment]
We have no plans to add a flag for skipping CA validation as that is bad practice and should be unnecessary. 

I got the tinify API client working with the mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim docker image as well.

@quentinR0bert Could you share what version of .netcore you are using?

**Comment by quentinR0bert** [comment]
Hi !

Thanks for the answer, we understand the bad practice about security.

The .Net Core CLI project target .Net Core 3.0 and the .Net Library with the Tinify NuGet target .Net Standard 2.1

**Comment by quentinR0bert** [comment]
FYI i have just downloaded the source code and executed the test as marked in the readme.

The "dotnet test test/Tinify.Tests" is okay.

but i have 4 failed test for the Integration tests (by default the sample is on .netCore 2.0, i have the same error in .netCore 3.0 and 3.1)

(Some MSBuild part is in french sorry :-/ )
[output.txt](https://github.com/tinify/tinify-net/files/7425616/output.txt)

**Comment by rkoopmans** [comment]
Thanks for sharing! I can confirm that the client does not work on mac OS.

Currently it works on:
Linux - dotnet > 3.1
Windows - dotnet > 2.0

Since it seems to be dotnet implementation specific to mac OS or underlying libraries, we are not looking into this right now. I suggest you use Docker for building and running your dotnet app.
